apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)

    scope "/tasks" do
      get("/create_contract_methods", TaskController, :create_contract_methods, as: :create_contract_methods)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.GraphQL

  forward("/wobserver", Wobserver.Web.Router)
  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
    pipe_through(:api)

    get("/supply", SupplyController, :supply)

    resources("/decompiled_smart_contract", DecompiledSmartContractController, only: [:create])
  end

  scope "/api", BlockScoutWeb.API.RPC do
    pipe_through(:api)

    alias BlockScoutWeb.API.RPC

    forward("/", RPCTranslator, %{
      "block" => RPC.BlockController,
      "account" => RPC.AddressController,
      "logs" => RPC.LogsController,
      "token" => RPC.TokenController,
      "stats" => RPC.StatsController,
      "contract" => RPC.ContractController,
      "transaction" => RPC.TransactionController
    })
  end

  # Needs to be 200 to support the schema introspection for graphiql
  @max_complexity 200

  forward("/graphql", Absinthe.Plug,
    schema: BlockScoutWeb.Schema,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  forward("/graphiql", Absinthe.Plug.GraphiQL,
    schema: BlockScoutWeb.Schema,
    interface: :advanced,
    default_query: GraphQL.default_query(),
    socket: BlockScoutWeb.UserSocket,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  # Disallows Iframes (write routes)
  scope "/", BlockScoutWeb do
    pipe_through(:browser)
  end

  # Allows Iframes (read-only routes)
  scope "/", BlockScoutWeb do
    pipe_through([:browser, BlockScoutWeb.Plug.AllowIframe])

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources("/market_history_chart", Chain.MarketHistoryChartController, only: [:show], singleton: true)

    resources "/blocks", BlockController, only: [:index, :show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    resources("/pending_transactions", PendingTransactionController, only: [:index])

    resources("/recent_transactions", RecentTransactionsController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal_transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token_transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal_transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/decompiled_contracts",
        AddressDecompiledContractController,
        only: [:index],
        as: :decompiled_contract
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new, :create],
        as: :verify_contract
      )

      resources(
        "/read_contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token_transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token_balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )

      resources(
        "/coin_balances",
        AddressCoinBalanceController,
        only: [:index],
        as: :coin_balance
      )

      resources(
        "/coin_balances/by_day",
        AddressCoinBalanceByDayController,
        only: [:index],
        as: :coin_balance_by_day
      )
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token_transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read_contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token_holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )
    end

    resources(
      "/smart_contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/search", ChainController, :search)

    get("/token_autocomplete", ChainController, :token_autocomplete)

    get("/chain_blocks", ChainController, :chain_blocks, as: :chain_blocks)

    get("/api_docs", APIDocsController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
defmodule BlockScoutWeb.AddressTransactionController do
  @moduledoc """
    Display all the Transactions that terminate at this Address.
  """

  use BlockScoutWeb, :controller

  import BlockScoutWeb.AddressController, only: [transaction_count: 1, validation_count: 1]
  import BlockScoutWeb.Chain, only: [current_filter: 1, paging_options: 1, next_page_params: 3, split_list_by_page: 1]

  alias BlockScoutWeb.TransactionView
  alias Explorer.{Chain, Market}
  alias Explorer.ExchangeRates.Token
  alias Indexer.Fetcher.CoinBalanceOnDemand
  alias Phoenix.View

  @transaction_necessity_by_association [
    necessity_by_association: %{
      [created_contract_address: :names] => :optional,
      [from_address: :names] => :optional,
      [to_address: :names] => :optional,
      [token_transfers: :token] => :optional,
      [token_transfers: :to_address] => :optional,
      [token_transfers: :from_address] => :optional,
      [token_transfers: :token_contract_address] => :optional
    }
  ]

  def index(conn, %{"address_id" => address_hash_string, "type" => "JSON"} = params) do
    with {:ok, address_hash} <- Chain.string_to_address_hash(address_hash_string),
         {:ok, address} <- Chain.hash_to_address(address_hash) do
      options =
        @transaction_necessity_by_association
        |> put_in([:necessity_by_association, :block], :required)
        |> Keyword.merge(paging_options(params))
        |> Keyword.merge(current_filter(params))

      results_plus_one = Chain.address_to_transactions_with_rewards(address, options)
      {results, next_page} = split_list_by_page(results_plus_one)

      next_page_url =
        case next_page_params(next_page, results, params) do
          nil ->
            nil

          next_page_params ->
            address_transaction_path(
              conn,
              :index,
              address,
              Map.delete(next_page_params, "type")
            )
        end

      items_json =
        Enum.map(results, fn result ->
          case result do
            {%Chain.Block.Reward{} = emission_reward, %Chain.Block.Reward{} = validator_reward} ->
              View.render_to_string(
                TransactionView,
                "_emission_reward_tile.html",
                current_address: address,
                emission_funds: emission_reward,
                validator: validator_reward
              )

            %Chain.Transaction{} = transaction ->
              View.render_to_string(
                TransactionView,
                "_tile.html",
                current_address: address,
                transaction: transaction
              )
          end
        end)

      json(conn, %{items: items_json, next_page_path: next_page_url})
    else
      :error ->
        unprocessable_entity(conn)

      {:error, :not_found} ->
        not_found(conn)
    end
  end

  def index(conn, %{"address_id" => address_hash_string} = params) do
    with {:ok, address_hash} <- Chain.string_to_address_hash(address_hash_string),
         {:ok, address} <- Chain.hash_to_address(address_hash) do
      render(
        conn,
        "index.html",
        address: address,
        coin_balance_status: CoinBalanceOnDemand.trigger_fetch(address),
        exchange_rate: Market.get_exchange_rate(Explorer.coin()) || Token.null(),
        filter: params["filter"],
        transaction_count: transaction_count(address),
        validation_count: validation_count(address),
        current_path: current_path(conn)
      )
    else
      :error ->
        unprocessable_entity(conn)

      {:error, :not_found} ->
        not_found(conn)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/views/address_transaction_view.ex
defmodule BlockScoutWeb.AddressTransactionView do
  use BlockScoutWeb, :view

  def format_current_filter(filter) do
    case filter do
      "to" -> gettext("To")
      "from" -> gettext("From")
      _ -> gettext("All")
    end
  end
end

lib/explorer_web/controllers/address_transaction_controller.ex
defmodule ExplorerWeb.AddressTransactionController do
  use ExplorerWeb, :controller

  import Ecto.Query

  alias Explorer.Address
  alias Explorer.Repo.NewRelic, as: Repo
  alias Explorer.Transaction
  alias Explorer.TransactionForm

  def index(conn, %{"address_id" => address_id} = params) do
    hash = String.downcase(address_id)
    address = Repo.one(from address in Address,
      where: fragment("lower(?)", address.hash) == ^hash,
      limit: 1)
    address_id = address.id
    query = from transaction in Transaction,
      join: block in assoc(transaction, :block),
      join: receipt in assoc(transaction, :receipt),
      join: from_address in assoc(transaction, :from_address),
      join: to_address in assoc(transaction, :to_address),
      preload: [:block, :receipt, :to_address, :from_address],
      order_by: [desc: transaction.inserted_at],
      where: to_address.id == ^address_id or from_address.id == ^address_id
    page = Repo.paginate(query, params)
    entries = Enum.map(page.entries, &TransactionForm.build_and_merge/1)
    render(conn, "index.html", transactions: Map.put(page, :entries, entries))
  end
end

lib/explorer_web/views/address_transaction_view.ex
defmodule ExplorerWeb.AddressTransactionView do
  use ExplorerWeb, :view
  @dialyzer :no_match
end

lib/explorer_web/templates/address_transaction/index.html.eex
<section class="container__section block">
  <div class="address__headline">
    <h1 class="address__headline-title"><%= gettext("Address %{number}", number: @conn.params["address_id"]) %></h1>
    <div class="address__pagination"><%= pagination_links @conn, @transactions, ["en", @conn.params["address_id"]], view_style: :bulma, first: true, distance: 1, previous: Phoenix.HTML.raw("&lsaquo;"), next: Phoenix.HTML.raw("&rsaquo;"), path: &address_transaction_path/5 %></div>
  </div>
  <div class="address__container">
    <div class="address__tabs">
      <h2 class="address__tab"><%= link(gettext("Overview"), to: address_path(@conn, :show, @conn.assigns.locale, @conn.params["address_id"]), class: "address__link") %></h2>
      <h2 class="address__tab address__tab--active"><%= link(gettext("Transactions"), to: address_transaction_path(@conn, :index, @conn.assigns.locale, @conn.params["address_id"]), class: "address__link address__link--active") %></h2>
    </div>
    <div class="transactions__container">
      <table class="transactions__table">
        <thead class="transactions__header">
          <tr>
            <th class="transactions__column-header transactions__column-header--status"><span class="transactions__column-title transactions__column-title--status"><%= gettext "Status" %></span></th>
            <th class="transactions__column-header"><%= gettext "Hash" %></th>
            <th class="transactions__column-header transactions__column-header--optional"><%= gettext "Block" %></th>
            <th class="transactions__column-header"><%= gettext "Age" %></th>
            <th class="transactions__column-header transactions__column-header--optional"><%= gettext "From" %></th>
            <th class="transactions__column-header transactions__column-header--optional"><%= gettext "To" %></th>
            <th class="transactions__column-header"><%= gettext "Value" %></th>
          </tr>
        </thead>
        <tbody>
          <%= for transaction <- @transactions do %>
            <tr class="transactions__row">
              <td class="transactions__column transactions__column--status"><div class="transactions__dot transactions__dot--<%= transaction.status %>"></div></td>
              <td class="transactions__column transactions__column--hash">
                <div class="transactions__hash"><%= link(transaction.hash, to: transaction_path(@conn, :show, @conn.assigns.locale, transaction.hash), class: "transactions__link transactions__link--truncated transactions__link--long-hash") %></div>
              </td>
              <td class="transactions__column transactions__column--block transactions__column--optional">
                <%= link(transaction.block.number, to: block_path(@conn, :show, @conn.assigns.locale, transaction.block.number), class: "transactions__link") %>
              </td>
              <td class="transactions__column transactions__column--age">
                <%= transaction.block.timestamp |> Timex.from_now %>
              </td>
              <td class="transactions__column transactions__column--from transactions__column--optional">
                <div class="transactions__hash"><%= link(transaction.from_address.hash, to: address_path(@conn, :show, @conn.assigns.locale, transaction.from_address.hash), class: "transactions__link transactions__link--truncated transactions__link--hash") %></div>
              </td>
              <td class="transactions__column transactions__column--to transactions__column--optional">
                <div class="transactions__hash"><%= link(transaction.to_address.hash, to: address_path(@conn, :show, @conn.assigns.locale, transaction.to_address.hash), class: "transactions__link transactions__link--truncated transactions__link--hash") %></div>
              </td>
              <td class="transactions__column transactions__column--value"><%= Decimal.div(Decimal.new(transaction.value), Decimal.new(1_000_000_000_000_000_000)) |> Decimal.to_string(:normal) %> <%= gettext "POA" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>