apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)

    scope "/tasks" do
      get("/create_contract_methods", TaskController, :create_contract_methods, as: :create_contract_methods)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.GraphQL

  forward("/wobserver", Wobserver.Web.Router)
  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
    pipe_through(:api)

    get("/supply", SupplyController, :supply)

    resources("/decompiled_smart_contract", DecompiledSmartContractController, only: [:create])
  end

  scope "/api", BlockScoutWeb.API.RPC do
    pipe_through(:api)

    alias BlockScoutWeb.API.RPC

    forward("/", RPCTranslator, %{
      "block" => RPC.BlockController,
      "account" => RPC.AddressController,
      "logs" => RPC.LogsController,
      "token" => RPC.TokenController,
      "stats" => RPC.StatsController,
      "contract" => RPC.ContractController,
      "transaction" => RPC.TransactionController
    })
  end

  # Needs to be 200 to support the schema introspection for graphiql
  @max_complexity 200

  forward("/graphql", Absinthe.Plug,
    schema: BlockScoutWeb.Schema,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  forward("/graphiql", Absinthe.Plug.GraphiQL,
    schema: BlockScoutWeb.Schema,
    interface: :advanced,
    default_query: GraphQL.default_query(),
    socket: BlockScoutWeb.UserSocket,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  # Disallows Iframes (write routes)
  scope "/", BlockScoutWeb do
    pipe_through(:browser)
  end

  # Allows Iframes (read-only routes)
  scope "/", BlockScoutWeb do
    pipe_through([:browser, BlockScoutWeb.Plug.AllowIframe])

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources("/market_history_chart", Chain.MarketHistoryChartController, only: [:show], singleton: true)

    resources "/blocks", BlockController, only: [:index, :show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    resources("/pending_transactions", PendingTransactionController, only: [:index])

    resources("/recent_transactions", RecentTransactionsController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal_transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token_transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal_transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/decompiled_contracts",
        AddressDecompiledContractController,
        only: [:index],
        as: :decompiled_contract
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new, :create],
        as: :verify_contract
      )

      resources(
        "/read_contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token_transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token_balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )

      resources(
        "/coin_balances",
        AddressCoinBalanceController,
        only: [:index],
        as: :coin_balance
      )

      resources(
        "/coin_balances/by_day",
        AddressCoinBalanceByDayController,
        only: [:index],
        as: :coin_balance_by_day
      )
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token_transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read_contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token_holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )
    end

    resources(
      "/smart_contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/search", ChainController, :search)

    get("/token_autocomplete", ChainController, :token_autocomplete)

    get("/chain_blocks", ChainController, :chain_blocks, as: :chain_blocks)

    get("/api_docs", APIDocsController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
defmodule BlockScoutWeb.AddressController do
  use BlockScoutWeb, :controller

  alias Explorer.{Chain, Market}
  alias Explorer.Chain.Address
  alias Explorer.ExchangeRates.Token

  def index(conn, _params) do
    render(conn, "index.html",
      address_tx_count_pairs: Chain.list_top_addresses(),
      address_count: Chain.count_addresses_with_balance_from_cache(),
      exchange_rate: Market.get_exchange_rate(Explorer.coin()) || Token.null(),
      total_supply: Chain.total_supply()
    )
  end

  def show(conn, %{"id" => id}) do
    redirect(conn, to: address_transaction_path(conn, :index, id))
  end

  def transaction_count(%Address{} = address) do
    Chain.total_transactions_sent_by_address(address)
  end

  def validation_count(%Address{} = address) do
    Chain.address_to_validation_count(address)
  end
end

apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
<div class="card card-primary" data-test="outside_of_dropdown">
  <div class="card-body">
    <span></span>
    <h2 class="card-title text-white balance-card-title"><%= gettext "Balance" %></h2>
    <div class="text-right">
      <h3 class="text-white" data-test="address_balance"><%= balance(@address) %></h3>
      <%= if !match?({:pending, _}, @coin_balance_status) && !empty_exchange_rate?(@exchange_rate) do %>
        <span class="text-white text-faded">
          <span class="current-balance-in-wei"
            data-wei-value="<%= if @address.fetched_coin_balance, do: @address.fetched_coin_balance.value %>"
              data-usd-exchange-rate="<%= @exchange_rate.usd_value %>">
          </spanc>
          <small>(@ <span data-usd-unit-price="<%= @exchange_rate.usd_value %>"></span>/<%= gettext("Ether") %>)</small>
          <br>
        </span>
      <% end %>

      <div class="mt-3" data-token-balance-dropdown data-api_path="<%= address_token_balance_path(BlockScoutWeb.Endpoint, :index, @address.hash) %>">
          <div data-loading class="mb-0 text-white text-faded">
            <span class="loading-spinner-small mr-2">
              <span class="loading-spinner-block-1"></span>
              <span class="loading-spinner-block-2"></span>
            </span>
            <%= gettext("Fetching tokens...") %>
          </div>

          <div data-error-message class="mb-0 text-white text-faded" style="display: none;">
            <%= gettext("Error trying to fetch balances.") %>
          </div>
      </div>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
<%= if @address do %>
  <%= link to: address_path(BlockScoutWeb.Endpoint, :show, @address), "data-test": "address_hash_link", class: assigns[:class] do %>
    <%= render BlockScoutWeb.AddressView, "_responsive_hash.html", address: @address, contract: @contract, truncate: assigns[:truncate] %>
  <% end %>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/address/_metatags.html.eex
<%= if assigns[:address] do %>
  <title>
    <%= gettext(
          "%{address} - %{subnetwork} Explorer",
          address: BlockScoutWeb.AddressView.address_page_title(@address),
          subnetwork: LayoutView.subnetwork_title()
        ) %>
  </title>
  <meta name="description" content="<%= gettext "View the account balance, transactions, and other data for %{address} on the %{network}", address: to_string(@address), network: LayoutView.network_title() %>">
  <meta name="keywords" content="<%= BlockScoutWeb.AddressView.address_page_title(@address) <> ", " <> Explorer.coin() <> ", "<> LayoutView.network_title() %>">
<% else %>
  <title>
    <%= gettext "Top Accounts - %{subnetwork} Explorer", subnetwork: LayoutView.subnetwork_title() %>
  </title>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
<span class="<%= if @contract do %>contract-address<% end %>" data-address-hash="<%= @address %>">
  <%= if name = primary_name(@address) do %>
     <span data-toggle="tooltip" data-placement="top" title="<%= @address %>"><%= name %> (<%= short_hash(@address) %>...)</span>
  <% else %>
    <%= if assigns[:truncate] do %>
      <%= BlockScoutWeb.AddressView.trimmed_hash(@address.hash) %>
    <% else %>
      <span class="d-none d-md-none d-lg-inline"><%= @address %></span>
      <span class="d-md-inline-block d-lg-none"><%= BlockScoutWeb.AddressView.trimmed_hash(@address.hash) %></span>
    <% end %>
  <% end %>
</span>

apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
<!-- DESKTOP TAB NAV -->
<ul class="nav nav-tabs card-header-tabs d-none d-lg-inline-flex">
  <li class="nav-item">
    <%= link(
          gettext("Transactions"),
          class: "nav-link #{tab_status("transactions", @conn.request_path)}",
          to: address_transaction_path(@conn, :index, @address.hash)
        ) %>
  </li>

  <li class="nav-item">
    <%= link(
          gettext("Tokens"),
          class: "nav-link #{tab_status("tokens", @conn.request_path)}",
          to: address_token_path(@conn, :index, @address.hash),
          "data-test": "tokens_tab_link"
        ) %>
  </li>

  <li class="nav-item"> <%= link(
          gettext("Internal Transactions"),
          class: "nav-link #{tab_status("internal_transactions", @conn.request_path)}",
          "data-test": "internal_transactions_tab_link",
          to: address_internal_transaction_path(@conn, :index, @address.hash)
        ) %>
  </li>

  <li class="nav-item">
    <%= link(
          gettext("Coin Balance History"),
          class: "nav-link #{tab_status("coin_balances", @conn.request_path)}",
          "data-test": "coin_balance_tab_link",
          to: address_coin_balance_path(@conn, :index, @address.hash)
        ) %>
  </li>

  <%= if BlockScoutWeb.AddressView.validator?(@validation_count) do %>
    <li class="nav-item">
      <%= link(
        gettext("Blocks Validated"),
        class: "nav-link #{tab_status("validations", @conn.request_path)}",
        "data-test": "validations_tab_link",
        to: address_validation_path(@conn, :index, @address.hash)
      ) %>
    </li>
  <% end %>

  <%= if contract?(@address) do %>
    <li class="nav-item">
      <%= link(
          to: address_contract_path(@conn, :index, @address.hash),
          class: "nav-link #{tab_status("contracts", @conn.request_path)}") do %>
          <%= gettext("Code") %>

        <%= if smart_contract_verified?(@address) do %>
          <i class="far fa-check-circle text-success"></i>
        <% end %>
      <% end %>
    </li>
  <% end %>

  <%= if has_decompiled_code?(@address) do %>
    <li class="nav-item">
      <%= link(
          to: address_decompiled_contract_path(@conn, :index, @address.hash),
          class: "nav-link #{tab_status("decompiled_contracts", @conn.request_path)}") do %>
          <%= gettext("Decompiled code") %>
          <i class="far fa-check-circle text-success"></i>
       <% end %>
    </li>
  <% end %>

  <%= if smart_contract_with_read_only_functions?(@address) do %>
    <li class="nav-item">
      <%= link(
          gettext("Read Contract"),
          to: address_read_contract_path(@conn, :index, @address.hash),
          class: "nav-link #{tab_status("read_contract", @conn.request_path)}")%>
    </li>
  <% end %>
</ul>

<!-- MOBILE DROPDOWN NAV -->
<ul class="nav nav-tabs card-header-tabs d-lg-none">
  <li class="nav-item dropdown flex-fill text-center">
    <a class="nav-link active dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      <%= current_tab_name(@conn.request_path) %>
    </a>
    <div class="dropdown-menu">
      <%= link(
            gettext("Transactions"),
            class: "dropdown-item #{tab_status("transactions", @conn.request_path)}",
            to: address_transaction_path(@conn, :index, @address.hash)
          ) %>
      <%= link(
            gettext("Tokens"),
            class: "dropdown-item  #{tab_status("tokens", @conn.request_path)}",
            to: address_token_path(@conn, :index, @address.hash)
          ) %>
      <%= link(
            gettext("Internal Transactions"),
            class: "dropdown-item #{tab_status("internal_transactions", @conn.request_path)}",
            "data-test": "internal_transactions_tab_link",
            to: address_internal_transaction_path(@conn, :index, @address.hash)
          ) %>
      <%= link(
            gettext("Coin Balance History"),
            class: "dropdown-item #{tab_status("coin_balances", @conn.request_path)}",
            "data-test": "coin_balance_tab_link",
            to: address_coin_balance_path(@conn, :index, @address.hash)
          ) %>
      <%= if validator?(@validation_count) do %>
        <%= link(
          gettext("Blocks Validated"),
          class: "dropdown-item",
          "data-test": "validations_tab_link",
          to: address_validation_path(@conn, :index, @address.hash)
        ) %>
      <% end %>
      <%= if contract?(@address) do %>
        <%= link(
            to: address_contract_path(@conn, :index, @address.hash),
            class: "dropdown-item #{tab_status("contracts", @conn.request_path)}") do %>
          <%= gettext("Code") %>

          <%= if smart_contract_verified?(@address) do %>
            <i class="far fa-check-circle"></i>
          <% end %>

          <%= if has_decompiled_code?(@address) do %>
            <%= link(
                to: address_decompiled_contract_path(@conn, :index, @address.hash),
                class: "dropdown-item #{tab_status("contracts", @conn.request_path)}") do %>
             <%= gettext("Decompiled code") %>
             <i class="far fa-check-circle text-success"></i>
          <% end %>
        <% end %>
        <% end %>
      <% end %>
      <%= if smart_contract_with_read_only_functions?(@address) do %>
        <%= link(
            gettext("Read Contract"),
            to: address_read_contract_path(@conn, :index, @address.hash),
            class: "dropdown-item #{tab_status("read_contract", @conn.request_path)}")%>
      <% end %>
    </div>
  </li>
</ul>

apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
<div class="tile">
  <div class="row">
    <!-- rank -->
    <div class="col-2 col-md-1 d-flex justify-content-center align-items-center">
      <!-- incremented number by order in the list -->
      <span>
        <%= @index %>
      </span>
    </div>

    <div class="col-10 col-md-11">
      <div class="row">
        <div class="col-md-6 d-flex flex-column">
          <%= @address |> BlockScoutWeb.AddressView.address_partial_selector(nil, nil) |> BlockScoutWeb.RenderHelpers.render_partial() %>
          <!-- number of txns for this address -->
          <span class="mr-4">
            <span data-test="transaction_count">
              <%= @tx_count %>
            </span> <%= gettext "Transactions sent" %>
            <% if validator?(@address) do %>
              <span data-test="validation_count">
                <%= @validation_count %>
              </span> <%= gettext "Validations" %>
            <% end %>
          </span>
        </div>

        <!-- balance and percentage -->
        <div class="col-md-6 d-flex flex-column text-md-right mt-3 mt-md-0">
          <!-- address coin balance -->
          <span class="tile-title" data-test="address_balance"><%= balance(@address) %></span>
          <div class="d-flex flex-column flex-md-row justify-content-md-end">
            <!-- USD value of the balance -->
            <span
              data-wei-value="<%= if @address.fetched_coin_balance, do: @address.fetched_coin_balance.value %>"
              <% if !empty_exchange_rate?(@exchange_rate) do %>
                data-usd-exchange-rate="<%= @exchange_rate.usd_value %>">
              <% end %>
            </span>
            <!-- percentage of coins from total supply -->
            <span class="ml-0 ml-md-2">(<%= balance_percentage(@address, @total_supply) %>)</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

apps/block_scout_web/lib/block_scout_web/templates/address/_validator_metadata_modal.html.eex
  <div class="modal fade" id="validatorModal" tabindex="-1" role="dialog" aria-labelledby="validatorModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="validatorModalLabel"><%= gettext"Validator Data" %></h2>
        </div>
        <div class="modal-body">
          <h1 class="text-center"><%= @address_name %></h1>
          <div class="row mt-2">
            <div class="col-sm-4 text-right text-muted"><%= gettext"License ID" %></div>
            <div class="col-sm-8">
              <%= @validator_metadata["license_id"] %>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-sm-4 text-right text-muted"><%= gettext"Address" %></div>
            <div class="col-sm-8">
             <%= @validator_metadata["address"] %>,
             <%= @validator_metadata["state"] %>,
             <%= @validator_metadata["zipcode"] %>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-sm-4 text-right text-muted"><%= gettext"License Expires" %></div>
            <div class="col-sm-8">
             <%= format_datetime_string(@validator_metadata["expiration_date"]) %>
            </div>
          </div>
          <div class="row mt-2">
            <div class="col-sm-4 text-right text-muted"><%= gettext"Validator Creation Date" %></div>
            <div class="col-sm-8">
              <%= format_datetime_string(@validator_metadata["created_date"]) %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal"><%= gettext "Close" %></button>
        </div>
      </div>
    </div>
  </div>

apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
<section class="container">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title margin-bottom-0"><%= gettext "Addresses" %></h1>
      <p class="card-subtitle">
        <%= gettext "Showing 250 addresses of" %>
        <%= Cldr.Number.to_string!(@address_count, format: "#,###") %>
        <%= gettext "total addresses with a balance" %>
      </p>
      <span data-selector="top-addresses-list">
        <%= for {{address, tx_count}, index} <- Enum.with_index(@address_tx_count_pairs, 1) do %>
          <%= render "_tile.html",
            address: address, index: index, exchange_rate: @exchange_rate,
            total_supply: @total_supply, tx_count: tx_count,
            validation_count: validation_count(address) %>
        <% end %>
      </span>
    </div>
  </div>
</section>

apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
<section class="address-overview" data-page="address-details" data-page-address-hash="<%= @address.hash %>">
  <div class="row">
    <div class="card-section col-md-12 col-lg-8">
      <div class="card">
        <div class="card-body">
          <div class="icon-links float-right">
            <span data-clipboard-text="<%= @address %>">
              <button type="button" class="icon-link" id="button" data-toggle="tooltip" data-placement="top" title="<%= gettext("Copy Address") %>" aria-label="<%= gettext("Copy Address") %>">
                <i class="fas fa-clone"></i>
              </button>
            </span>
            <span data-toggle="modal" data-target="#qrModal">
              <button type="button" class="icon-link"  data-toggle="tooltip" data-placement="top" title="<%= gettext("QR Code") %>" aria-label="<%= gettext("Show QR Code") %>">
                <i class="fas fa-qrcode"></i>
              </button>
            </span>
            <%= if validator_metadata = primary_validator_metadata(@address) do %>
              <span data-toggle="modal" data-target="#validatorModal">
                <button type="button" class="icon-link"  data-toggle="tooltip" data-placement="top" title="<%= gettext("Validator Info") %>" aria-label="<%= gettext("Show Validator Info") %>">
                  <i class="fas fa-address-card"></i>
                </button>
              </span>
            <% end %>
          </div>
          <h1 class="card-title"><%= address_title(@address) %> <%= gettext "Details" %> </h1>
          <h3 class="<%= if BlockScoutWeb.AddressView.contract?(@address) do %>contract-address<% end %>" data-test="address_detail_hash"><%= @address %></h3>
          <div class="d-flex flex-column flex-lg-row justify-content-start text-muted">
            <%= if address_name = primary_name(@address) do %>
              <strong class="mr-4 mb-2 text-primary"><%= address_name %></strong>
            <% end %>
            <%= if @address.token do %>
              <span class="mr-4 mb-2">
                <%= link(token_title(@address.token), to: token_path(@conn, :show, @address.hash), "data-test": "token_hash_link" ) %>
              </span>
            <% end %>
            <span>
              <span class="address-detail-item">
                <%= if contract?(@address) do %>
                  <%= gettext(">=") %>
                  <span data-selector="transaction-count">
                    <%= incoming_transaction_count(@address) %>
                  </span>
                  <%= gettext("Incoming Transactions") %>
                <% else %>
                  <span data-selector="transaction-count">
                    <%= Cldr.Number.to_string!(@transaction_count, format: "#,###") %>
                  </span>
                  <%= gettext("Transactions Sent") %>
                <% end %>
              </span>
              <span class="address-detail-item">
                <%= gettext("Last Balance Update: Block #") %><span data-selector="fetched-coin-balance-block-number"><%= @address.fetched_coin_balance_block_number %></span>
              </span>
              <%= if validator?(@validation_count) do %>
                <span class="address-detail-item">
                  <span data-selector="validation-count">
                    <%= Cldr.Number.to_string!(@validation_count, format: "#,###") %>
                  </span>
                  <%= gettext("Blocks Validated") %>
                </span>
              <% end %>
            </span>
          </div>
          <% from_address_hash = from_address_hash(@address) %>

          <%= if contract?(@address) do %>
            <span class="text-muted" data-test="address_contract_creator">
              <%= if from_address_hash do %>
                <%= gettext "Created by" %>
                <%= link(
                  trimmed_hash(from_address_hash(@address)),
                  to: address_path(@conn, :show, from_address_hash(@address))
                ) %>

                <%= gettext "at" %>

                <%= link(
                  trimmed_hash(transaction_hash(@address)),
                  to: transaction_path(@conn, :show, transaction_hash(@address)),
                  "data-test": "transaction_hash_link"
                ) %>
              <% else %>
                <p class="alert alert-danger" role="alert"><%= gettext("Error: Could not determine contract creator.") %></p>
              <% end %>
            </span>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card-section col-md-12 col-lg-4" data-selector="balance-card">
      <%= render BlockScoutWeb.AddressView, "_balance_card.html", conn: @conn, address: @address, exchange_rate: @exchange_rate, coin_balance_status: @coin_balance_status %>
    </div>

  </div>
</section>

<!-- Modal QR -->
<div class="modal fade" id="qrModal" tabindex="-1" role="dialog" aria-labelledby="qrModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="qrModalLabel"><%= gettext "QR Code" %></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="<%= gettext("Close") %>">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="data:image/png;base64, <%= qr_code(@address) %>" class="qr-code" alt="qr_code" title="<%= @address %>" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal"><%= gettext "Close" %></button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Validator -->
<%= if validator_metadata do %>
  <%= render BlockScoutWeb.AddressView, "_validator_metadata_modal.html", address_name: address_name, validator_metadata: validator_metadata %>
<% end %>